create extension if not exists pgcrypto;

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 60),
  song_name text not null check (char_length(song_name) between 1 and 120),
  file_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.songs enable row level security;

create or replace function public.enforce_song_limit()
returns trigger language plpgsql security definer set search_path=public
as $$
declare n integer;
begin
  perform pg_advisory_xact_lock(736215);
  select count(*) into n from public.songs;
  if n >= 60 then raise exception 'The 60-song limit has been reached.'; end if;
  return new;
end;
$$;

drop trigger if exists song_limit on public.songs;
create trigger song_limit before insert on public.songs for each row execute function public.enforce_song_limit();

drop policy if exists "public read songs" on public.songs;
create policy "public read songs" on public.songs for select to anon, authenticated using (true);

drop policy if exists "public insert songs" on public.songs;
create policy "public insert songs" on public.songs for insert to anon, authenticated with check (true);

drop policy if exists "admin delete songs" on public.songs;
create policy "admin delete songs" on public.songs for delete to authenticated using (true);

insert into storage.buckets (id,name,public) values ('songs','songs',true)
on conflict (id) do update set public=true;

drop policy if exists "public upload songs" on storage.objects;
create policy "public upload songs" on storage.objects for insert to anon, authenticated
with check (bucket_id='songs');

drop policy if exists "public read song files" on storage.objects;
create policy "public read song files" on storage.objects for select to anon, authenticated
using (bucket_id='songs');

drop policy if exists "admin delete song files" on storage.objects;
create policy "admin delete song files" on storage.objects for delete to authenticated
using (bucket_id='songs');
